version: '3.8'

services:
  iitwelders-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    container_name: iitwelders-dev
    command: npm run dev

volumes:
  node_modules:
